In [40]:
%load_ext autoreload
%autoreload 2
import sys
import pandas as pd
sys.path.append("../..")
# This library will contain all the economic complexity variants I can implement
from libraries import ecomplexity as ec

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [41]:
# For ECI & Fitness, we only need MCP_exp
mcp_exp = pd.read_csv("../../data/processed/mcp_exp.csv", sep = "\t", dtype = {"prod": str})
mcp_exp

       exporter  prod      dollars       rca       rpop
0           ABW  0101      20082.0  0.031193   0.147798
1           ALB  0101     591083.0  0.485544   0.154471
2           ARE  0101  254637717.0  2.218371  21.129935
3           ARG  0101   83643277.0  2.035324   1.509173
4           ARM  0101       2491.0  0.003542   0.000652
...         ...   ...          ...       ...        ...
137336      USA  0103   98430498.0  0.060184   0.114419
137337      VNM  0103     583265.0  0.004125   0.002365
137338      ZAF  0103    2185848.0  0.020223   0.015022
137339      ZMB  0103      27816.0  0.003347   0.000693
137340      ZWE  0103      36260.0  0.012989   0.001003

[137341 rows x 5 columns]

In [43]:
# Let's calculate all complexities
eci_rca, pci_rca = ec.eci(mcp_exp, variant = "rca", threshold = 1)
eci_rpop, pci_rpop = ec.eci(mcp_exp, variant = "rpop", threshold = 0.25)
fit12_rca, compl12_rca = ec.fitness12(mcp_exp, variant = "rca", threshold = 1)
fit12_rpop, compl12_rpop = ec.fitness12(mcp_exp, variant = "rpop", threshold = 0.25)
fit12_rca

    exporter  fitness12
0        ABW   0.103507
1        AFG   0.205833
2        AGO   0.000044
3        ALB   0.531469
4        ARE   0.373723
..       ...        ...
159      VNM   1.619043
160      YEM   0.033184
161      ZAF   1.052638
162      ZMB   0.209657
163      ZWE   0.173081

[164 rows x 2 columns]

In [44]:
# We save them in a temporary file that we can merge later to our experimental measures
# We start from the country complexities
ecis = eci_rca.merge(eci_rpop, on = "exporter", suffixes = ("_rca", "_rpop"))
fitnesses = fit12_rca.merge(fit12_rpop, on = "exporter", suffixes = ("_rca", "_rpop"))
country_df = ecis.merge(fitnesses, on = "exporter")
country_df.to_csv("literature_complexities_country.csv", sep = "\t", index = False)
country_df

    exporter   eci_rca  eci_rpop  fitness12_rca  fitness12_rpop
0        ABW  0.122585  0.838788       0.103507        0.745492
1        AFG -0.865256 -1.656564       0.205833        0.003582
2        AGO -1.205506 -0.984400       0.000044        0.001116
3        ALB -0.311605  0.063788       0.531469        0.253260
4        ARE  0.190255  0.799657       0.373723        3.080079
..       ...       ...       ...            ...             ...
159      VNM  0.131371  0.600881       1.619043        1.023054
160      YEM -1.398730 -1.461118       0.033184        0.004185
161      ZAF  0.227489  0.603744       1.052638        1.422032
162      ZMB -0.375720 -0.359686       0.209657        0.086567
163      ZWE -0.789590 -1.150576       0.173081        0.027022

[164 rows x 5 columns]

In [45]:
# And now the product complexities
pcis = pci_rca.merge(pci_rpop, on = "prod", suffixes = ("_rca", "_rpop"))
complexities = compl12_rca.merge(compl12_rpop, on = "prod", suffixes = ("_rca", "_rpop"))
product_df = pcis.merge(complexities, on = "prod")
product_df.to_csv("literature_complexities_products.csv", sep = "\t", index = False)
product_df

     prod   pci_rca  pci_rpop  complexity12_rca  complexity12_rpop
0    0101  0.051523  0.150809          0.381792           0.062694
1    0102 -0.774190 -1.694987          0.096540           0.007353
2    0103  0.707527  0.765032          1.515456           3.532749
3    0104 -1.468719 -3.134917          0.105449           0.006282
4    0105  0.026584  0.256036          0.430872           1.275749
..    ...       ...       ...               ...                ...
989  9618  0.250713  0.788611          1.428552           1.544157
990  9701  0.757788  0.704754          0.325362           1.219200
991  9703 -0.063414  0.549070          0.482100           0.858265
992  9705 -0.809279 -0.504732          0.082997           0.226543
993  9706 -1.649034 -0.911182          0.027102           0.158030

[994 rows x 5 columns]