In [1]:
# This is experimental code, that is why it didn't make it to the ecomplexity library yet. Still working on it...
import sys
import numpy as np
import pandas as pd
import networkx as nx
from collections import defaultdict
sys.path.append("../..")
from libraries import network_distance as nd

In [2]:
# Loading the input. We need the Product Spaces (both RCA and RPOP)
# We also need MCP exp
ps_rca = nx.read_edgelist("ps_nc_bb_0.01_rca.csv", delimiter = "\t", data = [("count", int), ("significance", float)], nodetype = str)
ps_rpop = nx.read_edgelist("ps_nc_bb_0.1_rpop.csv", delimiter = "\t", data = [("count", int), ("significance", float)], nodetype = str)
mcp_exp = pd.read_csv("../../data/processed/mcp_exp.csv", sep = "\t", dtype = {"prod": str})
mcp_exp

       exporter  prod      dollars       rca       rpop
0           ABW  0101      20082.0  0.031193   0.147798
1           ALB  0101     591083.0  0.485544   0.154471
2           ARE  0101  254637717.0  2.218371  21.129935
3           ARG  0101   83643277.0  2.035324   1.509173
4           ARM  0101       2491.0  0.003542   0.000652
...         ...   ...          ...       ...        ...
137336      USA  0103   98430498.0  0.060184   0.114419
137337      VNM  0103     583265.0  0.004125   0.002365
137338      ZAF  0103    2185848.0  0.020223   0.015022
137339      ZMB  0103      27816.0  0.003347   0.000693
137340      ZWE  0103      36260.0  0.012989   0.001003

[137341 rows x 5 columns]

In [13]:
# Let's set up some mock parameters that will make it easier to integrate this code into the library
variant = "rpop"
threshold = 1

In [14]:
# Since the Product Space is constant, we can cache Q for the calculation of the network variance
# As we'll have to use it for every exporter
mcp_rca = pd.pivot_table(data = mcp_exp, index = "prod", columns = "exporter", values = variant).fillna(0.0) >= threshold

if variant == "rca":
    G = ps_rca
    Q = nd._resistance(ps_rca)
elif variant == "rpop":
    G = ps_rpop
    Q = nd._resistance(ps_rpop)

Q

array([[0.        , 0.44363188, 0.45088508, ..., 2.05601177, 1.72927008,
        1.49534142],
       [0.44363188, 0.        , 0.27843601, ..., 2.02021839, 1.68660137,
        1.4454823 ],
       [0.45088508, 0.27843601, 0.        , ..., 2.02448525, 1.69172435,
        1.45136335],
       ...,
       [2.05601177, 2.02021839, 2.02448525, ..., 0.        , 2.61884946,
        2.47168492],
       [1.72927008, 1.68660137, 1.69172435, ..., 2.61884946, 0.        ,
        2.20731262],
       [1.49534142, 1.4454823 , 1.45136335, ..., 2.47168492, 2.20731262,
        0.        ]])

In [15]:
# We now build a dataframe exporter by exporter, by calculating its network variance over the Product Space
exp_variance = []
for exporter in mcp_rca:
    # We need the vector to be a probabiity distribution
    exporter_p = mcp_rca[exporter] / mcp_rca[exporter].sum()
    exp_variance.append((
        exporter,
        nd.variance(exporter_p, G, shortest_path_lengths = Q, kernel = "resistance")
    ))

exp_variance = pd.DataFrame(data = exp_variance, columns = ("exporter", f"var_{variant}"))
exp_variance

    exporter  var_rpop
0        ABW  0.948828
1        AFG  0.069057
2        AGO  0.074250
3        ALB  0.281332
4        ARE  1.131100
..       ...       ...
159      VNM  0.587735
160      YEM  0.057315
161      ZAF  0.460394
162      ZMB  0.322239
163      ZWE  0.072229

[164 rows x 2 columns]

In [16]:
exp_variance.to_csv(f"variance_complexity_{variant}.csv", index = False, sep = "\t")